### PR TITLE
Fix build adjust logos

### PR DESCRIPTION
**Pull request by spoonben**
Hopefully fix travis build.
Change my talk description.
Adjust sponsor logos for mobile.

### CODE REVIEW

**Comment by spoonben** [comment]
Build has been running for 10+ minutes. Stuck at 
```
Built project successfully. Stored in "/home/travis/build/LibertyJS/libertyjs.github.io-dev/tmp/class-tests_dist-rTc8OtkL.tmp".
```

Any consolation though, the bower install includes hammer now, so the local build won't fail if someone pulls this down to develop for it. 

```
Build successful - 4017ms.
```

**Comment by pselle** [comment]
Yeah Travis doesn't deploy and it's kinda broken? So yeah we can merge and
deploy this :)

**Comment by spoonben** [comment]
Sounds good to me :grin:

**Comment by belcherj** [comment]
Merged, I'll build to prod tonight

**Pull request merged**
